backend:
  name: github
  repo: abbas-rasekh/chipia.ir
  branch: main
  base_url: https://chipia.ir/
  auth_endpoint: /api/auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
